<?php

namespace Wali\FilamentWordExport\Support;

use PhpOffice\PhpWord\PhpWord;

class WordTemplateBuilder
{
    public static function applyBranding(PhpWord $phpWord): void
    {
        $section = $phpWord->getSections()[0];
        $header = $section->addHeader();
        $header->addText('Generated by Filament Word Export Plugin', ['italic' => true, 'size' => 10]);

        $footer = $section->addFooter();
        $footer->addText('Confidential', ['color' => '999999', 'size' => 9]);
    }
}
