blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/wali/filament-word-export/blob/main/README.md
    about: Check the documentation for usage examples and configuration options
  - name: 💬 Discussions
    url: https://github.com/wali/filament-word-export/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: mailto:w.dafalla@qu.edu.sa
    about: Please report security vulnerabilities privately via email
