<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Storage Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the storage disk used for temporary export files.
    |
    */
    'storage_disk' => 'local',

    /*
    |--------------------------------------------------------------------------
    | Header Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the document header settings. Set 'enabled' to false to
    | disable headers entirely.
    |
    */
    'header' => [
        'enabled' => true,
        'text' => 'Generated by Filament Word Export Plugin',
        'style' => [
            'italic' => true,
            'size' => 10,
            'color' => '000000',
            'alignment' => 'center', // left, center, right
        ],
        // Optional: Path to logo image file (relative to storage disk)
        'logo' => [
            'enabled' => false,
            'path' => null, // e.g., 'logos/company-logo.png'
            'width' => 100, // pixels
            'height' => 50, // pixels
            'alignment' => 'left', // left, center, right
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Footer Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the document footer settings. Set 'enabled' to false to
    | disable footers entirely.
    |
    */
    'footer' => [
        'enabled' => true,
        'text' => 'Generated via Filament Word Export Plugin',
        'style' => [
            'italic' => false,
            'size' => 9,
            'color' => '999999',
            'alignment' => 'center', // left, center, right
        ],
        // Show page numbers in footer
        'show_page_numbers' => true,
        'page_number_format' => 'Page {PAGE} of {NUMPAGES}',
        'page_number_alignment' => 'right', // left, center, right
    ],

    /*
    |--------------------------------------------------------------------------
    | Legacy Configuration (Deprecated)
    |--------------------------------------------------------------------------
    |
    | These options are maintained for backward compatibility but are
    | deprecated. Use the 'header' and 'footer' sections above instead.
    |
    */
    'brand_logo' => null, // Deprecated: Use header.logo instead
    'default_footer_text' => 'Generated via Filament Word Export Plugin', // Deprecated: Use footer.text instead
];
