name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality (PHP ${{ matrix.php }})

    strategy:
      fail-fast: false
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check code style (Pint)
        run: composer lint:test

      - name: Run static analysis (Rector dry-run)
        run: composer refactor:dry

  security:
    runs-on: ubuntu-latest
    name: Security Audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run security audit
        run: composer audit

  compatibility:
    runs-on: ubuntu-latest
    name: Laravel ${{ matrix.laravel }} & Filament ${{ matrix.filament }} Compatibility

    strategy:
      fail-fast: false
      matrix:
        include:
          - laravel: '11.*'
            filament: '^3.0'
            php: 8.3
          - laravel: '11.*'
            filament: '^4.0'
            php: 8.3
          - laravel: '12.*'
            filament: '^4.0'
            php: 8.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-filament-${{ matrix.filament }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-filament-${{ matrix.filament }}-
            ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies with specific Laravel and Filament versions
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "filament/filament:${{ matrix.filament }}" --no-update --dev
          composer update --prefer-dist --no-progress --with-all-dependencies

      - name: Verify Laravel and Filament versions
        run: |
          composer show laravel/framework
          composer show filament/filament

      - name: Check compatibility
        run: composer lint:test

      - name: Run static analysis
        run: composer refactor:dry
